version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/ativos/producao.webservices.ativo.com_temp
  - source: public/index.php
    destination: /var/www/ativos/.repo/producao.webservices.ativo.com
permissions:
  - object: /var/www/ativos/producao.webservices.ativo.com_temp
    owner: php-fpm
    group: php-fpm
  - object: /var/www/ativos/.repo/producao.webservices.ativo.com
    owner: root
    group: root
    mode: 444
hooks:
  AfterInstall:
    - location: codedeploy_scripts/AfterInstall.sh
      timeout: 120
      runas: root